# Generated by Django 3.2.5 on 2021-07-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerkrapin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('idnumber', models.IntegerField()),
                ('dob', models.DateField()),
                ('mobilenumber', models.IntegerField()),
                ('town', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('box', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
